// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconMdi:accountOutline': typeof import('~icons/mdi/account-outline')['default']
    'IconMdi:bellOutline': typeof import('~icons/mdi/bell-outline')['default']
    'IconMdi:car': typeof import('~icons/mdi/car')['default']
    'IconMdi:expandMore': typeof import('~icons/mdi/expand-more')['default']
    'IconMdi:keepOutline': typeof import('~icons/mdi/keep-outline')['default']
    'IconMdi:messageTextOutline': typeof import('~icons/mdi/message-text-outline')['default']
    'IconSimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
